export component Metadata {
    in property <string> title;
    in property <string> artist;
    in property <color> text_color: black;

    VerticalLayout {
        Text {
            text: title;
            font-size: 14px;
            font-weight: 600;
            color: root.text_color;
        }

        Text {
            text: artist;
            font-size: 12px;
            color: root.text_color;
        }
    }
}
