import { Calc } from "../func/calc.slint";

struct VinylArmAngles {
    min: angle,
    max: angle,
    resting: angle,
    base: angle,
}

// A rather complex component
// Children are put between the head & arm layer
export component VinylArm {
    in property <bool> is_playing;
    in property <float> position_secs;
    in property <float> length_secs;
    in property <VinylArmAngles> angles;

    in property <length> arm_x;
    in property <length> arm_y;
    in property <length> arm_height;
    in property <length> arm_width: root.arm_height;

    in property <image> vinyl-arm-base;
    in property <image> vinyl-arm;

    private property <length> transform_origin_x: root.arm_width * (200.0 / 900.0);
    private property <length> transform_origin_y: root.arm_height * 0.5;

    Image {
        source: root.vinyl-arm-base;
        height: root.arm_height;
        width: root.arm_width;
        x: root.arm_x;
        y: root.arm_y;
        image-fit: contain;
        cache-rendering-hint: true;
        transform-rotation: root.angles.base;

        transform-origin: {
            x: root.transform_origin_x,
            y: root.transform_origin_y,
        };
    }

    @children

    private property <angle> playing-angle: Calc.linear-interpolation(
        root.position_secs, 0.0, root.length_secs, root.angles.min / 1deg, root.angles.max / 1deg) * 1deg;

    private property <angle> head-angle: root.angles.resting;

    states [
        playing when root.is-playing: {
            head-angle: root.playing-angle;
            in {
                animate head-angle {
                    duration: 400ms;
                    easing: ease-out;
                }
            }
        }
        resting when !root.is-playing: {
            head-angle: root.angles.resting;
            in {
                animate head-angle {
                    duration: 400ms;
                    easing: ease-out;
                }
            }
        }
    ]

    Image {
        source: root.vinyl-arm;
        height: root.arm_height;
        width: root.arm_width;
        x: root.arm_x;
        y: root.arm_y;
        image-fit: contain;
        transform-rotation: head-angle;

        transform-origin: {
            x: root.transform_origin_x,
            y: root.transform_origin_y,
        };
    }
}
