

import { MediaData } from "../../models/media-data.slint";
import { Calc } from "../../func/calc.slint";
import { Button, StandardButton } from "std-widgets.slint";
import { Vinyl } from "../../components/vinyl.slint";
import { PlayerCard } from "../../components/player-card.slint";

component ControlButton {
    in property <string> text;
    in property <color> text_color: black;
    callback on-click();

    VerticalLayout {

        Button {
            clicked => { root.on-click() }
        }

        Text {
            color: root.text_color;
            font-size: 12px;
            text: root.text;
            horizontal-alignment: center;
        }
    }
}

component Controls {
    in property <bool> is-playing;
    in property <color> text_color;

    callback play_pause();
    callback next();
    callback prev();

    HorizontalLayout {
        spacing: 16px;

        ControlButton {
            text: root.is-playing ? "Pause" : "Play";
            text_color: root.text_color;
            on-click => { root.play_pause() }
        }

        Rectangle { }

        ControlButton {
            text: "Prev";
            text_color: root.text_color;
            on-click => { root.prev() }
        }

        ControlButton {
            text: "Next";
            text_color: root.text_color;
            on-click => { root.next() }
        }
    }
}

component Metadata {
    in property <string> title;
    in property <string> artist;
    in property <color> text_color: black;

    VerticalLayout {
        spacing: 4px;
        Text {
            color: root.text_color;
            font-size: 12px;
            text: root.title;
        }

        Text {
            color: root.text_color;
            font-size: 12px;
            text: root.artist;
        }
    }
}

component PlayerHead {
    private property <angle> player-head-min: 80.0deg;
    private property <angle> player-head-max: 108.0deg;
    private property <angle> player-head-resting: 73deg;
    in property <bool> is_playing;
    in property <float> position_secs;
    in property <float> length_secs;

    private property <angle> head-angle: root.is-playing
        ? Calc.linear-interpolation(root.position_secs, 0.0, root.length_secs, player-head-min / 1deg, player-head-max / 1deg) * 1deg
        : player-head-resting;

    animate head-angle {
        duration: 400ms;
        easing: ease-out;
    }

    Image {
        source: @image-url("../../assets/vinyl-arm.svg");
        height: 100%;
        width: 100%;
        image-fit: contain;
        transform-rotation: head-angle;

        transform-origin: {
            x: self.width * (200.0 / 900.0),
            y: self.height * 0.5,
        };
    }
}

export component VinylPlayer {
    in property <MediaData> media_data;
    in property <float> vinyl_angle: 0.0;
    in property <float> position_secs: 0.0;

    callback play_pause();
    callback next();
    callback prev();

    width: 100%;
    height: 100%;

    PlayerCard {
        x: parent.width - self.width;
        y: parent.height - self.height;

        width: 80%;
        height: 100%;

        background: root.media_data.has_media ? root.media_data.dominant_color : #1a1a1a;
        border-top-left-radius: 24px; // TODO use radius defined in registry

        VerticalLayout {
            padding: 8px;
            spacing: 12px;
            alignment: end;
            Metadata {
                title: root.media_data.title;
                artist: root.media_data.artist;
                text_color: root.media_data.on_dominant_color;
            }

            Controls {
                text_color: root.media_data.on_dominant_color;
                is-playing: root.media_data.is-playing;
                play_pause => { root.play_pause() }
                next => { root.next() }
                prev => { root.prev() }
            }
        }
    }

    Vinyl {
        x: 0;
        y: 30px;
        width: 90%;
        height: self.width;
        album_art: media_data.album-art;
        vinyl_angle: root.vinyl_angle;
    }

    PlayerHead {
        x: 210px;
        y: -60px;
        height: 50%;
        width: self.height;
        is_playing: root.media_data.is-playing;
        position_secs: root.position-secs;
        length_secs: root.media_data.length-secs;
    }
}
