export struct SkinConfig {
    width: length,
    height: length,
    border_radius: length,
    border_top_left_radius: length,
    border_top_right_radius: length,
    border_bottom_left_radius: length,
    border_bottom_right_radius: length,
    transparent_background: bool,
}

export global SkinRegistry {
    pure public function get_config(skin_name: string) -> SkinConfig {
        if (skin_name.to_lowercase() == "compact-vinyl-player") {
            return {
                width: 300px,
                height: 420px,
                border_top_left_radius: 12px,
                transparent_background: true,
            };
        }
        if (skin-name.to-lowercase() == "realistic-vinyl-player") {
            return {
                width: 450px,
                height: 400px,
                border_radius: 12px,
                transparent_background: true,
            };
        }
        if (skin-name.to-lowercase() == "vinyl-card") {
            return {
                width: 500px,
                height: 150px,
                border-radius: 16px,
                transparent_background: true,
            };
        }
        if (skin_name.to_lowercase() == "card") {
            return {
                width: 300px,
                height: 60px,
                border_radius: 10px,
                transparent_background: false,
            };
        }
        return {
            width: 200px,
            height: 200px,
            border_radius: 0px,
            transparent_background: false,
        };
    }
}
