

import { MediaData } from "../../models/media-data.slint";
import { Calc } from "../../func/calc.slint";
import { Button, StandardButton } from "std-widgets.slint";
import { Vinyl } from "../../components/vinyl.slint";
import { PlayerCard } from "../../components/player-card.slint";
import { BaseSkin } from "../base-skin.slint";
import { Icons } from "../../icon_registry.slint";

component ControlButton {
    in property <image> image;
    in property <color> color; // on_dominant_color
    in property <bool> is_dark: true;
    callback on-click();

    VerticalLayout {
        spacing: 4px;

        Rectangle {
            width: 44px;
            height: 20px;

            Rectangle {
                width: 44px;
                height: 20px;
                border-radius: 6px;
                y: touch.pressed ? 2px : 0px;

                border-width: 1px;
                border-color: touch.pressed
                    ? root.color.with-alpha(0.30)
                    : touch.has-hover
                    ? root.color.with-alpha(0.60)
                    : root.color.with-alpha(0.40);

                background: touch.pressed
                    ? @linear-gradient(180deg, root.color.with-alpha(0.15) 0%, root.color.with-alpha(0.25) 100%)
                    : touch.has-hover
                    ? @linear-gradient(180deg, root.color.with-alpha(0.48) 0%, root.color.with-alpha(0.32) 100%)
                    : @linear-gradient(180deg, root.color.with-alpha(0.38) 0%, root.color.with-alpha(0.20) 100%);

                animate background, border-color {
                    duration: 100ms;
                    easing: ease-out;
                }
                animate y { duration: 40ms; }

                touch := TouchArea {
                    clicked => { root.on-click() }
                    mouse-cursor: pointer;
                }
            }
        }

        HorizontalLayout {
            alignment: center;
            Image {
                source: image;
                colorize: root.color;
                width: 100%;
                height: 24px;
            }
        }
    }
}


component Controls {
    in property <bool> is-playing;
    in property <color> text_color;
    in property <bool> is_dark: true;

    callback play_pause();
    callback next();
    callback prev();

    HorizontalLayout {
        spacing: 16px;

        ControlButton {
            image: root.is-playing ? Icons.pause : Icons.play;
            color: root.text_color;
            is_dark: root.is_dark;
            on-click => { root.play_pause() }
        }

        Rectangle { }

        ControlButton {
            image: Icons.back;
            color: root.text_color;
            is_dark: root.is_dark;
            on-click => { root.prev() }
        }

        ControlButton {
            image: Icons.forward;
            color: root.text_color;
            is_dark: root.is_dark;
            on-click => { root.next() }
        }
    }
}

component Metadata {
    in property <string> title;
    in property <string> artist;
    in property <color> text_color: black;

    VerticalLayout {
        spacing: 4px;
        Text {
            color: root.text_color;
            font-size: 12px;
            text: root.title;
        }

        Text {
            color: root.text_color;
            font-size: 12px;
            text: root.artist;
        }
    }
}

component PlayerBase {
    in property <image> source: @image-url("../../assets/vinyl-arm-base.svg");
    Image {
        source: root.source;
        height: 100%;
        width: 100%;
        image-fit: contain;
    }
}

component PlayerHead {
    private property <angle> player-head-min: 88.0deg;
    private property <angle> player-head-max: 111.0deg;
    private property <angle> player-head-resting: 76deg;
    in property <bool> is_playing;
    in property <float> position_secs;
    in property <float> length_secs;
    in property <image> source: @image-url("../../assets/vinyl-arm.svg");

    private property <angle> head-angle: root.is-playing
        ? Calc.linear-interpolation(root.position_secs, 0.0, root.length_secs, player-head-min / 1deg, player-head-max / 1deg) * 1deg
        : player-head-resting;

    animate head-angle {
        duration: 400ms;
        easing: ease-out;
    }

    Image {
        source: root.source;
        height: 100%;
        width: 100%;
        image-fit: contain;
        transform-rotation: head-angle;

        transform-origin: {
            x: self.width * (200.0 / 900.0),
            y: self.height * 0.5,
        };
    }
}

export component CompactVinylPlayer inherits BaseSkin {
    width: 100%;
    height: 100%;

    PlayerCard {
        x: parent.width - self.width;
        y: parent.height - self.height;

        width: 80%;
        height: 100%;

        background: root.media_data.has_media ? root.media_data.dominant_color : #1a1a1a;
        border-top-left-radius: 24px; // TODO use radius defined in registry

        VerticalLayout {
            padding: 8px;
            spacing: 12px;
            alignment: end;
            Metadata {
                title: root.media_data.title;
                artist: root.media_data.artist;
                text_color: root.media_data.on_dominant_color;
            }

            Controls {
                text_color: root.media_data.on_dominant_color;
                is_dark: root.media_data.is_dark;
                is-playing: root.media_data.is-playing;
                play_pause => { root.play_pause() }
                next => { root.next() }
                prev => { root.prev() }
            }
        }
    }

    PlayerBase {
        x: player-head.x;
        y: player-head.y;
        width: player-head.width;
        height: player-head.height;
    }

    Vinyl {
        x: 0;
        y: 30px;
        width: 90%;
        height: self.width;
        album_art: root.media_data.album-art;
        vinyl_angle: root.animation_state.vinyl-angle;
    }

    player-head := PlayerHead {
        x: 190px;
        y: -90px;
        height: 70%;
        width: self.height;
        is_playing: root.media_data.is-playing;
        position_secs: root.position-secs;
        length_secs: root.media_data.length-secs;
    }
}
