import { MediaData } from "../../models/media-data.slint";
import { Vinyl } from "../../components/vinyl.slint";
import { Visualizer } from "../../components/visualizer.slint";
import { VerticalBox, GroupBox } from "std-widgets.slint";
import { PlayerCard } from "../../components/player-card.slint";
import { BaseSkin } from "../base-skin.slint";

component Metadata {
    in property <string> title;
    in property <string> artist;
    in property <color> text_color: black;

    VerticalLayout {
        Text {
            text: title;
            font-size: 14px;
            font-weight: 600;
            color: root.text_color;
        }

        Text {
            text: artist;
            font-size: 12px;
            color: root.text_color;
        }
    }
}


export component VinylCard inherits BaseSkin {
    private property <length> margin: 8px;

    private property <bool> expanded: true;

    private property <length> vinyl_x: root.expanded
        ? root.margin
        : (root.width - vinyl.width - root.margin);
    private property <length> card_width: root.expanded
        ? (root.width * 0.9)
        : 0px;
    animate card_width, vinyl_x {
        duration: 500ms;
        easing: ease-out;
    }

    init => {
        root.visualizer-toggled(root.expanded);
    }

    width: 100%;
    height: 100%;

    PlayerCard {
        width: card_width;
        height: 80%;
        background: root.media_data.has_media ? root.media_data.dominant_color : #1a1a1a;
        // bg-image: root.media_data.blurred-art; // TODO hook this up to a setting
        // bg-image-opacity: 0.33; 
        x: root.width - self.width - root.margin;
        y: root.height * 0.5 - self.height * 0.5;
        border-radius: 16px; // TODO use radius defined in registry

         VerticalBox {
            padding-left: vinyl.width - root.width / 20; // why: accounts for the 5% margin on each side
            padding-bottom: 0px;

            Metadata {
                title: root.media_data.title;
                artist: root.media_data.artist;
                text_color: root.media_data.on_dominant_color;
            }

            Visualizer {
                bars: root.animation_state.bars;
                bar_color: root.media_data.text_color;
                height: parent.height * 0.6;
                width: 100%;
            }
        }
    }

    TouchArea {
        mouse-cursor: root.expanded ? e-resize : w-resize;
        clicked => {
            root.expanded = !root.expanded;
            root.visualizer-toggled(root.expanded);
        }
        x: vinyl_x;
        y: root.margin;

        width: vinyl.width;
        height: vinyl.height;

        vinyl := Vinyl {
            height: root.height - 2 * root.margin;
            width: self.height;
            album_art: root.media_data.album_art;
            vinyl_angle: root.animation_state.vinyl_angle;
        }
    }
}
