

import { MediaData } from "../../models/media-data.slint";
import { Vinyl } from "../../components/vinyl.slint";
import { Visualizer } from "../../components/visualizer.slint";
import { VerticalBox, GroupBox } from "std-widgets.slint";

component Metadata {
    in property <string> title;
    in property <string> artist;
    VerticalLayout {
        Text {
            text: title;
            font-size: 14px;
            font-weight: 600;
            color: black;
        }

        Text {
            text: artist;
            font-size: 12px;
            color: black;
        }
    }
}

component Card inherits Rectangle {
    in property <string> title;
    in property <string> artist;
    in property <length> vinyl-size;
    in property <[float]> visualizer_bars;

    clip: true;

    VerticalBox {
        padding-left: vinyl-size;
        padding-bottom: 0px;

        Metadata {
            title: root.title;
            artist: root.artist;
        }

        Visualizer {
            bars: root.visualizer_bars;
            height: parent.height * 0.6;
            width: 100%;
        }
    }
}


export component VinylCard inherits Rectangle {
    in property <MediaData> media_data;
    in property <float> vinyl_angle: 0.0;
    in property <float> animation_phase: 0.0;
    in property <[float]> visualizer_bars;
    private property <length> margin: 8px;

    private property <bool> expanded: true;

    private property <length> vinyl_x: root.expanded
        ? root.margin
        : (root.width - vinyl.width - root.margin);
    private property <length> card_width: root.expanded
        ? (root.width * 0.9)
        : 0px;
    animate card_width, vinyl_x {
        duration: 500ms;
        easing: ease-out;
    }

    callback visualizer-toggled(active: bool);

    init => {
        visualizer-toggled(root.expanded);
    }

    width: 100%;
    height: 100%;

    Card {
        width: card_width;
        height: 80%;
        background: yellow;
        x: root.width - self.width - root.margin;
        y: root.height * 0.5 - self.height * 0.5;
        border-radius: 16px; // TODO use radius defined in registry

        title: root.media_data.title;
        artist: root.media_data.artist;
        vinyl-size: vinyl.width - root.width / 20; // why: accounts for the 5% margin on each side
        visualizer_bars: root.visualizer_bars;
    }

    TouchArea {
        mouse-cursor: root.expanded ? e-resize : w-resize;
        clicked => {
            root.expanded = !root.expanded;
            root.visualizer-toggled(root.expanded);
        }
        x: vinyl_x;
        y: root.margin;

        width: vinyl.width;
        height: vinyl.height;

        vinyl := Vinyl {
            height: root.height - 2 * root.margin;
            width: self.height;
            album_art: root.media_data.album_art;
            vinyl_angle: root.vinyl_angle;
        }
    }
}
