import { CapyPlayer } from "capy-player.slint";
import { MediaData } from "models/media-data.slint";
import { AnimationState } from "models/animation-state.slint";
import { SkinRegistry, SkinConfig, SkinHost } from "skins/generated_skins.slint";
import { IconRegistry, Icons } from "icon_registry.slint";

export { SkinRegistry, SkinConfig, AnimationState, IconRegistry, Icons }
export component CapySpellPlayer inherits Window {
    in property <MediaData> media_data: {
        title: "Never Gonna Give You Up",
        artist: "Rick Astley",
        album: "Whenever You Need Somebody",
        length_secs: 200,
        position-secs: 0,
        is_playing: false,
        has_media: false,
        text_color: #000000,
        dominant_color: #0000ff,
        on_dominant_color: #ffffff,
        is_dark: false
    };
    in-out property <float> position_secs: 0;
    in-out property <float> vinyl_angle: 0.0;
    in-out property <float> animation_phase: 0.0;
    in-out property <[float]> visualizer_bars: [0.0, 0.0, 0.0, 0.0];

    private property <AnimationState> animation_state: {
        vinyl_angle: root.vinyl_angle,
        phase: root.animation_phase,
        bars: root.visualizer_bars,
    };

    in property <string> skin: "realistic-vinyl-player";

    out property <SkinConfig> current_skin: SkinRegistry.get_config(root.skin);
    out property <bool> visualizer_active;

    callback play_pause();
    callback next();
    callback prev();
    callback seek(float);

    width: root.current_skin.width;
    height: root.current_skin.height;
    background: transparent;

    SkinHost {
        skin: root.skin;
        media_data: root.media_data;
        position_secs: root.position_secs;
        animation_state: root.animation_state;

        play_pause => { root.play_pause() }
        next => { root.next() }
        prev => { root.prev() }
        seek(val) => { root.seek(val) }
        visualizer_toggled(active) => {
            root.visualizer_active = active;
        }
    }
}
