import { VerticalBox, Button } from "std-widgets.slint";
import { CapyPlayer } from "capy-player.slint";
import { MediaData } from "models/media-data.slint";

export component CapySpellPlayer inherits Window {
    in property <MediaData> media_data;
    in-out property <float> position_secs;

    callback play_pause();
    callback next();
    callback prev();
    callback seek(float);

    width: 376px;
    height: 576px;

    CapyPlayer {
        width: 100%;
        height: 100%;
        data: root.media_data;
        position_secs: root.position_secs;

        play-pause => { root.play_pause(); }
        next => { root.next(); }
        prev => { root.prev(); }
        seek(val) => { root.seek(val); }
    }
}
