import { VerticalBox, Button } from "std-widgets.slint";
import { CapyPlayer } from "capy-player.slint";
import { MediaData } from "models/media-data.slint";
import { SkinRegistry, SkinConfig } from "skins/skin_registry.slint";
import { VinylPlayer } from "skins/vinyl-player/vinyl-player.slint";
import { VinylCard } from "skins/vinyl-card/vinyl-card.slint";

export { SkinRegistry, SkinConfig }
export component CapySpellPlayer inherits Window {
    in property <MediaData> media_data;
    in-out property <float> position_secs;
    in-out property <float> vinyl_angle: 0.0;
    in-out property <float> animation_phase: 0.0;

    in property <string> skin: "vinyl-player";

    out property <SkinConfig> current_skin: SkinRegistry.get_config(root.skin);

    callback play_pause();
    callback next();
    callback prev();
    callback seek(float);

    width: root.current_skin.width;
    height: root.current_skin.height;
    background: transparent;

    if (root.skin.to-lowercase() == "vinyl-player"): 
    VinylPlayer {
        media_data: root.media_data;
        vinyl_angle: root.vinyl_angle;

        play_pause => { play_pause() }
        next => { next() }
        prev => { prev() }
    }
    if (root.skin.to-lowercase() == "vinyl-card"): 
    VinylCard {
        media_data: root.media_data;
        vinyl_angle: root.vinyl_angle;
        animation_phase: root.animation_phase;
    }
}
